package com.ridill.xpensetracker.core.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF006d39)
val LightOnPrimary = Color(0xFFffffff)
val LightPrimaryContainer = Color(0xFF8df9b0)
val LightOnPrimaryContainer = Color(0xFF00210d)
val LightSecondary = Color(0xFF4f6353)
val LightOnSecondary = Color(0xFFffffff)
val LightSecondaryContainer = Color(0xFFd2e8d4)
val LightOnSecondaryContainer = Color(0xFF0c1f12)
val LightTertiary = Color(0xFF3a646f)
val LightOnTertiary = Color(0xFFffffff)
val LightTertiaryContainer = Color(0xFFbeeaf7)
val LightOnTertiaryContainer = Color(0xFF001f26)
val LightError = Color(0xFFba1b1b)
val LightErrorContainer = Color(0xFFffdad4)
val LightOnError = Color(0xFFffffff)
val LightOnErrorContainer = Color(0xFF410001)
val LightBackground = Color(0xFFfbfdf7)
val LightOnBackground = Color(0xFF1a1c1a)
val LightSurface = Color(0xFFfbfdf7)
val LightOnSurface = Color(0xFF1a1c1a)
val LightSurfaceVariant = Color(0xFFdde5db)
val LightOnSurfaceVariant = Color(0xFF414942)
val LightOutline = Color(0xFF717971)
val LightInverseOnSurface = Color(0xFFf0f1ec)
val LightInverseSurface = Color(0xFF2e312e)

val DarkPrimary = Color(0xFF71dc96)
val DarkOnPrimary = Color(0xFF00391b)
val DarkPrimaryContainer = Color(0xFF005229)
val DarkOnPrimaryContainer = Color(0xFF8df9b0)
val DarkSecondary = Color(0xFFb6ccb9)
val DarkOnSecondary = Color(0xFF223527)
val DarkSecondaryContainer = Color(0xFF384b3c)
val DarkOnSecondaryContainer = Color(0xFFd2e8d4)
val DarkTertiary = Color(0xFFa2cdd9)
val DarkOnTertiary = Color(0xFF023640)
val DarkTertiaryContainer = Color(0xFF214c57)
val DarkOnTertiaryContainer = Color(0xFFbeeaf7)
val DarkError = Color(0xFFffb4a9)
val DarkErrorContainer = Color(0xFF930006)
val DarkOnError = Color(0xFF680003)
val DarkOnErrorContainer = Color(0xFFffdad4)
val DarkBackground = Color(0xFF1a1c1a)
val DarkOnBackground = Color(0xFFe1e3de)
val DarkSurface = Color(0xFF1a1c1a)
val DarkOnSurface = Color(0xFFe1e3de)
val DarkSurfaceVariant = Color(0xFF414942)
val DarkOnSurfaceVariant = Color(0xFFc0c9bf)
val DarkOutline = Color(0xFF8a938a)
val DarkInverseOnSurface = Color(0xFF1a1c1a)
val DarkInverseSurface = Color(0xFFe1e3de)

val Seed = Color(0xFF118c4f)
val Error = Color(0xFFba1b1b)